In [25]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer

In [26]:
breast = load_breast_cancer()
dir(breast)
data=breast.data
print(data)
target=breast.target
print(target)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [27]:
from sklearn.preprocessing import add_dummy_feature
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import mean_squared_error,accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.2,random_state=42)

In [29]:
log_reg=LogisticRegression(max_iter=10000)
log_reg.fit(x_train,y_train)
y_pred=log_reg.predict(x_test)

In [30]:
print(accuracy_score(y_test,y_pred))

0.956140350877193


In [31]:
confusion_matrix(y_test,y_pred)

array([[39,  4],
       [ 1, 70]])

In [32]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.97      0.91      0.94        43\n           1       0.95      0.99      0.97        71\n\n    accuracy                           0.96       114\n   macro avg       0.96      0.95      0.95       114\nweighted avg       0.96      0.96      0.96       114\n'

In [35]:
x=data
y=target
x_reg=x[:,[0]]
y_reg=x[:,2]

lin_reg=LinearRegression()

x_train_reg,x_test_red,y_train_reg,y_test_reg=train_test_split(x,y,test_size=0.2,random_state=42)

lin_reg.fit(x_train_reg,y_train_reg)
y_pred_reg=lin_reg.predict(x_test_red)

print(y_pred_reg)

mean_squared_error(y_test_reg,y_pred_reg)


[ 0.62168355  0.17803853  0.27512068  1.1320503   1.11698318 -0.66303713
 -0.07355607  0.44212355  0.28085763  0.96360261  0.794142    0.33192584
  0.90481757  0.39666504  0.9336697   0.17750175  0.91013271  1.19445658
  1.41615414  0.04464718  0.65041677  0.8752756  -0.38792384  1.08061015
  0.96215276  0.84678947  0.99807141  0.87049439  0.94386257 -0.16893149
  1.0238613   1.04190872  0.81604445  0.9156589   1.07186427  0.84289045
  0.48746626  0.62375262  0.25368547  0.76842229  1.15259719  0.03799193
  0.97126513  0.99773732  0.55160057  0.65587474  0.91828081  1.02580964
  0.80527854  1.01543748  0.20974453 -0.07875586  0.55842968  0.59037896
  1.02323689  0.78572959  0.93959678 -0.36416183  0.55847881  1.04937824
  0.94406266 -0.1953921  -0.35465216  0.80776979  0.90208492  0.58309865
 -0.16982229 -0.15422403  0.97877451  0.83434684  0.09123074  0.09531931
  0.8486583   0.25871356  0.9949576   0.83561759  0.80204781  0.58575204
  1.17901275  0.75766173  0.40996133  1.05654014  0

0.06410886247029474